name: "Setup Environment"
description: "Setting environment for the project"

inputs:
  task-version:
    description: "Task version"
    required: true
    default: "3.33.1"
  trivy-version:
    description: "Trivy version"
    required: true
    default: "v0.57.1"
  python-version:
    description: "Python version"
    required: true
    default: "3.12.1"
  with-python:
    description: "Python needed"
    required: true
    default: "true"
  poetry-version:
    description: "Poetry version"
    required: true
    default: "1.7.1"
  with-poetry:
    description: "Poetry needed"
    required: true
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Install Task
      uses: arduino/setup-task@v1
      with:
        version: ${{ inputs.task-version }}

    - name: Install Trivy
      uses: aquasecurity/setup-trivy@v0.2.2
      with:
        version: ${{ inputs.trivy-version }}

    - name: Set up Python
      if: ${{ inputs.with-python == 'true' }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install and configure Poetry
      if: ${{ inputs.with-poetry == 'true' }}
      uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry-version }}
