app:
  env: development
  debug: true
logs:
  level: DEBUG
tasks:
  config_backend:
    type: yaml_file
    path: .settings/config.yaml
  queue_backend:
    type: memory
  state_backend:
    type: local_dir
    path: .settings/state
