name: Check PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  check-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup_environment

      - name: Install Dependencies
        run: |
          task init

      - name: Lint PR
        run: |
          task lint

      - name: Test backend in container
        working-directory: backend
        run: |
          task test-container

      - name: Build backend image
        working-directory: backend
        run: |
          task image-build

      - name: Scan backend image
        id: scan
        uses: ovsds/run-with-output-action@v1
        continue-on-error: true
        with:
          run: task backend:image-scan

      - name: Report vulnerabilities
        uses: ovsds/create-or-update-unique-comment-action@v1
        with:
          issue-number: ${{ github.event.number }}
          body: |
            ## Vulnerabilities found
            ```
            ${{ steps.scan.outputs.stdout }}
            ```
          unique-body-includes: "## Vulnerabilities found"
          delete: ${{ steps.scan.outputs.exit_code == 0 }}
